language: python

matrix:
  include:
    - os: linux
      python: 2.7
      env:
        - COMPILER=gxx_linux-64
        - ANACONDA=https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
    - os: linux
      python: 3.6
      env:
        - COMPILER=gxx_linux-64
        - ANACONDA=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

git:
  submodules: false

install:
  - wget "${ANACONDA}" -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels potassco/label/dev
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install -q clingo cmake "${COMPILER}" ninja
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=release .
  - cmake --build .

script:
  - echo "&diff{a-0} <= 42." | ./bin/clingoDL || [ $? = 10 ]
