version: 1.0.{build}
clone_folder: c:\projects\clingoDL
configuration: Release
environment:
  matrix:
  - GEN: Visual Studio 14 2015 Win64
    PYTHON_VERSION: 3.6
before_build:
- cmd: >-
    conda config --set always_yes yes --set changeps1 no

    conda config --append channels potassco/label/dev

    conda update -q conda

    conda info -a

    conda create -q -n test-environment python=%PYTHON_VERSION%

    source activate test-environment

    conda install -q -n clingo cmake

    cmake -G "%GEN%" .

build:
  project: clingoDL.sln
  verbosity: minimal
test_script:
- cmd: >-

    cmake --build . --target install --config release

    clingoDL --version

    echo "&diff{x-0} <= 42." | clingoDL
