version: 1.0.{build}
clone_folder: c:\projects\clingoDL
configuration: Release

environment:
  matrix:
  - GEN: Visual Studio 14 2015 Win64
    PYTHON_VERSION: 3.6

before_build:
- cmd: >-

    set PATH=C:\Miniconda36-x64\Scripts;%PATH%

    activate

    conda config --set always_yes yes --set changeps1 no

    conda update -q conda

    conda info -a

    conda create -q -n test-environment python=%PYTHON_VERSION%

    activate test-environment

    conda install cmake 

    conda install -c potassco/label/dev clingo

    cmake -G "%GEN%" . -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX%\Library

build:
  project: clingoDL.sln
  verbosity: minimal

test_script:
- cmd: >-

    cmake --build . --target install --config release

    clingoDL --version

    python scratch/runtests.py

# this one should work but doesn't on appveyor ...
# echo ^^^&diff{x-0} ^^^<= 42. | clingoDL | findstr /b dl(x,\"0\")
